// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson21364dcaDecodeGithubComTechnoZoomersMasterHubBackendModels(in *jlexer.Lexer, out *Sdp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "sdp":
			out.Sdp = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson21364dcaEncodeGithubComTechnoZoomersMasterHubBackendModels(out *jwriter.Writer, in Sdp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sdp\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sdp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Sdp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson21364dcaEncodeGithubComTechnoZoomersMasterHubBackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Sdp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson21364dcaEncodeGithubComTechnoZoomersMasterHubBackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Sdp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson21364dcaDecodeGithubComTechnoZoomersMasterHubBackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Sdp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson21364dcaDecodeGithubComTechnoZoomersMasterHubBackendModels(l, v)
}
