// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels(in *jlexer.Lexer, out *Themes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Themes, 0, 1)
			} else {
				*out = Themes{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Theme
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels(out *jwriter.Writer, in Themes) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Themes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Themes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Themes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Themes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels(l, v)
}
func easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels1(in *jlexer.Lexer, out *Theme) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		case "theme":
			out.Theme = string(in.String())
		case "subthemes":
			if in.IsNull() {
				in.Skip()
				out.Subthemes = nil
			} else {
				in.Delim('[')
				if out.Subthemes == nil {
					if !in.IsDelim(']') {
						out.Subthemes = make([]string, 0, 4)
					} else {
						out.Subthemes = []string{}
					}
				} else {
					out.Subthemes = (out.Subthemes)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Subthemes = append(out.Subthemes, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels1(out *jwriter.Writer, in Theme) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		out.String(string(in.Theme))
	}
	{
		const prefix string = ",\"subthemes\":"
		out.RawString(prefix)
		if in.Subthemes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Subthemes {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Theme) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Theme) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1d9cf3aaEncodeGithubComTechnoZoomersMasterHubBackendModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Theme) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Theme) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1d9cf3aaDecodeGithubComTechnoZoomersMasterHubBackendModels1(l, v)
}
