// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels(in *jlexer.Lexer, out *VideosData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(VideosData, 0, 0)
			} else {
				*out = VideosData{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 VideoData
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels(out *jwriter.Writer, in VideosData) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v VideosData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VideosData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VideosData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VideosData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels(l, v)
}
func easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels1(in *jlexer.Lexer, out *VideoData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.Id = int64(in.Int64())
		case "intro":
			out.Intro = bool(in.Bool())
		case "name":
			out.Name = string(in.String())
		case "extension":
			out.FileExt = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "theme":
			(out.Theme).UnmarshalEasyJSON(in)
		case "rating":
			out.Rating = int64(in.Int64())
		case "uploaded":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Uploaded).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels1(out *jwriter.Writer, in VideoData) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Id != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Int64(int64(in.Id))
	}
	{
		const prefix string = ",\"intro\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Intro))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"extension\":"
		out.RawString(prefix)
		out.String(string(in.FileExt))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if true {
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		(in.Theme).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rating\":"
		out.RawString(prefix)
		out.Int64(int64(in.Rating))
	}
	{
		const prefix string = ",\"uploaded\":"
		out.RawString(prefix)
		out.Raw((in.Uploaded).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VideoData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VideoData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson93afa840EncodeGithubComTechnoZoomersMasterHubBackendModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VideoData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VideoData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson93afa840DecodeGithubComTechnoZoomersMasterHubBackendModels1(l, v)
}
