// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels(in *jlexer.Lexer, out *WebsocketNotification) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = int64(in.Int64())
		case "notification":
			(out.Notification).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels(out *jwriter.Writer, in WebsocketNotification) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Type))
	}
	{
		const prefix string = ",\"notification\":"
		out.RawString(prefix)
		(in.Notification).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WebsocketNotification) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WebsocketNotification) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WebsocketNotification) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WebsocketNotification) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels(l, v)
}
func easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels1(in *jlexer.Lexer, out *WebsocketMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = int64(in.Int64())
		case "message":
			(out.Message).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels1(out *jwriter.Writer, in WebsocketMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Type))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		(in.Message).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WebsocketMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WebsocketMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson717ebd13EncodeGithubComTechnoZoomersMasterHubBackendModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WebsocketMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WebsocketMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson717ebd13DecodeGithubComTechnoZoomersMasterHubBackendModels1(l, v)
}
